import { subDays } from "date-fns";
import { todayIso } from "./format";
import type { Account, Order, PortfolioState, Visit } from "./types";

function dateStr(daysAgo: number): string {
  const d = subDays(new Date(), daysAgo);
  return d.toISOString().slice(0, 10);
}

export function generateSampleWinePortfolio(): PortfolioState {
  const today = todayIso();

  const accounts: Account[] = [
    {
      id: "reserve-cut-steakhouse",
      name: "Reserve Cut Steakhouse",
      type: "restaurant",
      tier: "Platinum",
      licenseNumber: "CA-98210",
      city: "San Francisco",
      county: "San Francisco",
      region: "Bay Area",
      salesRep: "Marcus Vance",
    },
    {
      id: "bouchon-brasserie",
      name: "Bouchon Brasserie",
      type: "restaurant",
      tier: "Platinum",
      licenseNumber: "CA-44912",
      city: "Yountville",
      county: "Napa",
      region: "North Coast",
      salesRep: "Elena Rodriguez",
    },
    {
      id: "sonoma-coast-cellars",
      name: "Sonoma Coast Cellars",
      type: "club",
      tier: "Gold",
      licenseNumber: "CA-33819",
      city: "Santa Rosa",
      county: "Sonoma",
      region: "North Coast",
      salesRep: "Elena Rodriguez",
    },
    {
      id: "sunset-wine-lounge",
      name: "Sunset Wine Bar & Lounge",
      type: "bar",
      tier: "Gold",
      licenseNumber: "CA-77123",
      city: "Oakland",
      county: "Alameda",
      region: "East Bay",
      salesRep: "Marcus Vance",
    },
    {
      id: "grand-pacific-hotel",
      name: "Grand Pacific Hotel & Suites",
      type: "hotel",
      tier: "Platinum",
      licenseNumber: "CA-55102",
      city: "San Jose",
      county: "Santa Clara",
      region: "South Bay",
      salesRep: "Sarah Jenkins",
    },
    {
      id: "pacific-catch-seafood",
      name: "Pacific Catch Seafood Grill",
      type: "restaurant",
      tier: "Silver",
      licenseNumber: "CA-12844",
      city: "Monterey",
      county: "Monterey",
      region: "Central Coast",
      salesRep: "Sarah Jenkins",
    },
    {
      id: "cuvee-kitchen-bar",
      name: "Cuvée Kitchen & Bar",
      type: "restaurant",
      tier: "Silver",
      licenseNumber: "CA-66391",
      city: "Walnut Creek",
      county: "Contra Costa",
      region: "East Bay",
      salesRep: "Marcus Vance",
    },
    {
      id: "st-helena-table",
      name: "St. Helena Table",
      type: "restaurant",
      tier: "Bronze",
      licenseNumber: "CA-88120",
      city: "St. Helena",
      county: "Napa",
      region: "North Coast",
      salesRep: "Elena Rodriguez",
    },
    {
      id: "the-redwood-room",
      name: "The Redwood Room",
      type: "bar",
      tier: "Bronze",
      licenseNumber: "CA-21095",
      city: "San Rafael",
      county: "Marin",
      region: "Bay Area",
      salesRep: "Marcus Vance",
    },
    {
      id: "mission-trattoria",
      name: "Mission Trattoria",
      type: "restaurant",
      tier: "Silver",
      licenseNumber: "CA-39482",
      city: "San Francisco",
      county: "San Francisco",
      region: "Bay Area",
      salesRep: "Sarah Jenkins",
    },
  ];

  const orders: Order[] = [
    // Reserve Cut Steakhouse — Active, high volume, Platinum
    {
      id: "ord-rc-1",
      accountId: "reserve-cut-steakhouse",
      accountName: "Reserve Cut Steakhouse",
      date: dateStr(110),
      revenue: 3800,
      cases: 22,
      product: "Napa Valley Cabernet Sauvignon",
    },
    {
      id: "ord-rc-2",
      accountId: "reserve-cut-steakhouse",
      accountName: "Reserve Cut Steakhouse",
      date: dateStr(75),
      revenue: 4200,
      cases: 25,
      product: "Russian River Pinot Noir",
    },
    {
      id: "ord-rc-3",
      accountId: "reserve-cut-steakhouse",
      accountName: "Reserve Cut Steakhouse",
      date: dateStr(40),
      revenue: 4600,
      cases: 28,
      product: "Reserve Bordeaux Blend",
    },
    {
      id: "ord-rc-4",
      accountId: "reserve-cut-steakhouse",
      accountName: "Reserve Cut Steakhouse",
      date: dateStr(8),
      revenue: 5100,
      cases: 30,
      product: "Napa Valley Cabernet Sauvignon",
    },

    // Bouchon Brasserie — Steady Healthy
    {
      id: "ord-bb-1",
      accountId: "bouchon-brasserie",
      accountName: "Bouchon Brasserie",
      date: dateStr(90),
      revenue: 2900,
      cases: 18,
      product: "Carneros Chardonnay",
    },
    {
      id: "ord-bb-2",
      accountId: "bouchon-brasserie",
      accountName: "Bouchon Brasserie",
      date: dateStr(62),
      revenue: 3100,
      cases: 20,
      product: "Sonoma Coast Pinot Noir",
    },
    {
      id: "ord-bb-3",
      accountId: "bouchon-brasserie",
      accountName: "Bouchon Brasserie",
      date: dateStr(35),
      revenue: 3200,
      cases: 21,
      product: "Brut Prestige Sparkling",
    },
    {
      id: "ord-bb-4",
      accountId: "bouchon-brasserie",
      accountName: "Bouchon Brasserie",
      date: dateStr(12),
      revenue: 3400,
      cases: 22,
      product: "Carneros Chardonnay",
    },

    // Sonoma Coast Cellars — Healthy
    {
      id: "ord-scc-1",
      accountId: "sonoma-coast-cellars",
      accountName: "Sonoma Coast Cellars",
      date: dateStr(80),
      revenue: 2200,
      cases: 15,
      product: "Sauvignon Blanc",
    },
    {
      id: "ord-scc-2",
      accountId: "sonoma-coast-cellars",
      accountName: "Sonoma Coast Cellars",
      date: dateStr(52),
      revenue: 2400,
      cases: 16,
      product: "Sonoma Valley Syrah",
    },
    {
      id: "ord-scc-3",
      accountId: "sonoma-coast-cellars",
      accountName: "Sonoma Coast Cellars",
      date: dateStr(21),
      revenue: 2500,
      cases: 17,
      product: "Sonoma Coast Pinot Noir",
    },

    // Sunset Wine Bar — At Risk (last order ~48 days ago, typical cadence was 25 days)
    {
      id: "ord-swb-1",
      accountId: "sunset-wine-lounge",
      accountName: "Sunset Wine Bar & Lounge",
      date: dateStr(130),
      revenue: 2800,
      cases: 20,
      product: "Estate Cabernet Sauvignon",
    },
    {
      id: "ord-swb-2",
      accountId: "sunset-wine-lounge",
      accountName: "Sunset Wine Bar & Lounge",
      date: dateStr(100),
      revenue: 2600,
      cases: 18,
      product: "Old Vine Zinfandel",
    },
    {
      id: "ord-swb-3",
      accountId: "sunset-wine-lounge",
      accountName: "Sunset Wine Bar & Lounge",
      date: dateStr(72),
      revenue: 2100,
      cases: 14,
      product: "Sauvignon Blanc",
    },
    {
      id: "ord-swb-4",
      accountId: "sunset-wine-lounge",
      accountName: "Sunset Wine Bar & Lounge",
      date: dateStr(48),
      revenue: 1600,
      cases: 10,
      product: "Estate Cabernet Sauvignon",
    },

    // Grand Pacific Hotel — At Risk (slipping volume and visits)
    {
      id: "ord-gph-1",
      accountId: "grand-pacific-hotel",
      accountName: "Grand Pacific Hotel & Suites",
      date: dateStr(125),
      revenue: 6200,
      cases: 40,
      product: "Banquet Chardonnay",
    },
    {
      id: "ord-gph-2",
      accountId: "grand-pacific-hotel",
      accountName: "Grand Pacific Hotel & Suites",
      date: dateStr(95),
      revenue: 5400,
      cases: 35,
      product: "Banquet Cabernet",
    },
    {
      id: "ord-gph-3",
      accountId: "grand-pacific-hotel",
      accountName: "Grand Pacific Hotel & Suites",
      date: dateStr(55),
      revenue: 3800,
      cases: 25,
      product: "Brut Cuvee",
    },

    // Pacific Catch Seafood — Critical (no orders in 90+ days)
    {
      id: "ord-pcs-1",
      accountId: "pacific-catch-seafood",
      accountName: "Pacific Catch Seafood Grill",
      date: dateStr(150),
      revenue: 1800,
      cases: 14,
      product: "Dry Riesling",
    },
    {
      id: "ord-pcs-2",
      accountId: "pacific-catch-seafood",
      accountName: "Pacific Catch Seafood Grill",
      date: dateStr(115),
      revenue: 1600,
      cases: 12,
      product: "Crisp Sauvignon Blanc",
    },
    {
      id: "ord-pcs-3",
      accountId: "pacific-catch-seafood",
      accountName: "Pacific Catch Seafood Grill",
      date: dateStr(92),
      revenue: 1200,
      cases: 9,
      product: "Chardonnay by the Glass",
    },

    // Cuvée Kitchen & Bar — Critical (last order 88 days ago)
    {
      id: "ord-ckb-1",
      accountId: "cuvee-kitchen-bar",
      accountName: "Cuvée Kitchen & Bar",
      date: dateStr(140),
      revenue: 2100,
      cases: 16,
      product: "Pinot Grigio",
    },
    {
      id: "ord-ckb-2",
      accountId: "cuvee-kitchen-bar",
      accountName: "Cuvée Kitchen & Bar",
      date: dateStr(88),
      revenue: 1400,
      cases: 10,
      product: "Rhone Red Blend",
    },

    // St. Helena Table — Dormant / Critical (last order 110 days ago)
    {
      id: "ord-sht-1",
      accountId: "st-helena-table",
      accountName: "St. Helena Table",
      date: dateStr(160),
      revenue: 1500,
      cases: 11,
      product: "Merlot Reserve",
    },
    {
      id: "ord-sht-2",
      accountId: "st-helena-table",
      accountName: "St. Helena Table",
      date: dateStr(110),
      revenue: 1100,
      cases: 8,
      product: "Sauvignon Blanc",
    },

    // The Redwood Room — Healthy
    {
      id: "ord-rr-1",
      accountId: "the-redwood-room",
      accountName: "The Redwood Room",
      date: dateStr(70),
      revenue: 1900,
      cases: 14,
      product: "Bourbon Barrel Zinfandel",
    },
    {
      id: "ord-rr-2",
      accountId: "the-redwood-room",
      accountName: "The Redwood Room",
      date: dateStr(42),
      revenue: 2100,
      cases: 15,
      product: "Alexander Valley Merlot",
    },
    {
      id: "ord-rr-3",
      accountId: "the-redwood-room",
      accountName: "The Redwood Room",
      date: dateStr(16),
      revenue: 2200,
      cases: 16,
      product: "Old Vine Zinfandel",
    },

    // Mission Trattoria — New Account (first order 18 days ago)
    {
      id: "ord-mt-1",
      accountId: "mission-trattoria",
      accountName: "Mission Trattoria",
      date: dateStr(18),
      revenue: 1750,
      cases: 12,
      product: "Chianti Classico & Sangiovese",
    },
  ];

  const visits: Visit[] = [
    {
      id: "vis-rc-1",
      accountId: "reserve-cut-steakhouse",
      accountName: "Reserve Cut Steakhouse",
      date: dateStr(10),
      salesRep: "Marcus Vance",
      outcome: "Spring wine dinner menu finalized; placed 30cs order.",
    },
    {
      id: "vis-bb-1",
      accountId: "bouchon-brasserie",
      accountName: "Bouchon Brasserie",
      date: dateStr(14),
      salesRep: "Elena Rodriguez",
      outcome: "Staff tasting conducted for new vintage Chardonnay.",
    },
    {
      id: "vis-scc-1",
      accountId: "sonoma-coast-cellars",
      accountName: "Sonoma Coast Cellars",
      date: dateStr(25),
      salesRep: "Elena Rodriguez",
      outcome: "Checked retail display inventory; stock is moving well.",
    },
    {
      id: "vis-swb-1",
      accountId: "sunset-wine-lounge",
      accountName: "Sunset Wine Bar & Lounge",
      date: dateStr(18),
      salesRep: "Marcus Vance",
      outcome: "Met with sommelier; discussed slow BTG turnover.",
    },
    {
      id: "vis-swb-2",
      accountId: "sunset-wine-lounge",
      accountName: "Sunset Wine Bar & Lounge",
      date: dateStr(6),
      salesRep: "Marcus Vance",
      outcome: "Follow-up tasting; buyer requested written discount for 10cs.",
    },
    {
      id: "vis-gph-1",
      accountId: "grand-pacific-hotel",
      accountName: "Grand Pacific Hotel & Suites",
      date: dateStr(45),
      salesRep: "Sarah Jenkins",
      outcome: "F&B director meeting on catering contract renewal.",
    },
    {
      id: "vis-pcs-1",
      accountId: "pacific-catch-seafood",
      accountName: "Pacific Catch Seafood Grill",
      date: dateStr(35),
      salesRep: "Sarah Jenkins",
      outcome: "Sample drop-off; buyer was unavailable.",
    },
    {
      id: "vis-ckb-1",
      accountId: "cuvee-kitchen-bar",
      accountName: "Cuvée Kitchen & Bar",
      date: dateStr(28),
      salesRep: "Marcus Vance",
      outcome: "Dropped off summer rosé samples; left price sheet.",
    },
    {
      id: "vis-mt-1",
      accountId: "mission-trattoria",
      accountName: "Mission Trattoria",
      date: dateStr(20),
      salesRep: "Sarah Jenkins",
      outcome: "New account onboarding tasting; placed initial opening order.",
    },
  ];

  return {
    analysisAsOf: today,
    reports: [
      {
        id: "sample-orders-report",
        fileName: "Sample Wine Distribution Book.xlsx",
        kind: "orders",
        uploadedAt: today,
        rowCount: orders.length + accounts.length + visits.length,
      },
    ],
    accounts,
    orders,
    visits,
  };
}
